# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_test <- function(test) {
    .Call(`_statidea_c_test`, test)
}

c_two_arm_diff <- function(dat) {
    .Call(`_statidea_c_two_arm_diff`, dat)
}

